### PR TITLE
Change Action for Initializing Cache

### PR DESCRIPTION
**Pull request by 0aveRyan**
Running conditional checks `is_feed()` and `is_404()` was always returning `false` because those conditionals are set during the query (props @afragen).

I have some questions I'm going to raise in standup tmw

### CODE REVIEW

**Comment by afragen** [comment]
I've been testing this and I'm still not convinced that I don't see the same errors. ☹️

**Comment by afragen** [comment]
I think #57 fixes this issue.

**Comment by wpscholar** [comment]
@0aveRyan I see that this is still a draft. It seems like it may be a preferred solution, but I'm not sure what testing you've done. Anything you want to share about what you've found or what further work needs to be done?  Thanks!

**Comment by afragen** [comment]
@wpscholar changing the hook doesn't fix the issue for me.

**Comment by earnjam** [comment]
#57 was merged in 426e0a1ac2af169eaf3eb2301e38094d70f4eb38 which should resolve the `is_feed()` and `is_404()` issues. Do we still want to change the cache initialization action?

**Comment by 0aveRyan** [comment]
@earnjam we definitely should address still, that patch only prevents notices/fatals for undefined functions. due to the timing of the action hook, those checks are always returning false so all feeds and 404s are being cached.

**Pull request closed without merging**
